# Generated by Django 6.0.2 on 2026-03-27 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Guru'), ('principal', 'Kepala Sekolah')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('original_video', models.FileField(upload_to='videos/raw/')),
                ('preprocessed_dir', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('processing', 'Diproses'), ('completed', 'Selesai'), ('failed', 'Gagal')], default='pending', max_length=20)),
                ('total_faces', models.PositiveIntegerField(default=0)),
                ('model_score', models.FloatField(default=0.0)),
                ('predicted_label', models.CharField(blank=True, max_length=100)),
                ('process_log', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
