# Generated by Django 6.0.2 on 2026-04-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_videosubmission_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosubmission',
            name='ground_truth_breakdown',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='videosubmission',
            name='ground_truth_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='videosubmission',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
